"""Views, one for each Insta485 page."""
from insta485.views.index import show_index
from insta485.views.index import login
from insta485.views.index import accounts
from insta485.views.index import download_file
from insta485.views.index import likes
from insta485.views.index import comments
from insta485.views.index import logout
from insta485.views.index import create
from insta485.views.index import delete
from insta485.views.index import edit
from insta485.views.index import password
from insta485.views.index import post_redirect
from insta485.views.index import posts
from insta485.views.index import explore
from insta485.views.index import follower
from insta485.views.index import following
from insta485.views.index import following_redirect
from insta485.views.index import users
